### ISSUE TITLE
Compiles standard white theme

### ISSUE THREAD

**Issue by ikbenignace** [HeavyWolfPL/grav-theme-darkquark#1]
Hi

When running gulp, you get the standard Quark Theme again.
Did you only change the .css files instead of .scss?

**Comment by Wafelowski** [comment]
That's not good, thanks for letting me know I'll check it most likely today.

**Comment by ikbenignace** [comment]
Nice :) I already made my own style, but it's important to change the colors in the scss files. After that you can compile with gulp :)
That's the way intended to be.

**Comment by Wafelowski** [comment]
So I've made a new test branch to test if the changes work, but I don't have any way to test them currently.

**Comment by Wafelowski** [comment]
Should be fixed, but yet I have no way to test it currently.
