### ISSUE TITLE
Blog mode shows posts with white frame

### ISSUE THREAD

**Issue by crinavar** [HeavyWolfPL/grav-theme-darkquark#2]
Hi, thanks for the theme you make, I like it a lot.
Currently am having a problem when showing blog posts on the main blog page. The posts appear with a white frame, when they should blend with the dark theme instead. Here is a live example of our current site
https://patagon.uach.cl/
Any ideas where should I change something?

**Comment by Wafelowski** [comment]
I didn't test blogs, so here's the result of my laziness. I've changed the blog tabs background to #1c1e1f, but I don't have any way to test them. Latest release should have it fixed

**Comment by crinavar** [comment]
Hi HeavyWolf,
Many thanks, updated the theme and disabled "production mode", now it works good
https://patagon.uach.cl/
I am very new to grav, do you know when would I want to enable production mode?
