### ISSUE TITLE
Titles in Blog mode and order of posts

### ISSUE THREAD

**Issue by crinavar** [HeavyWolfPL/grav-theme-darkquark#4]
Hi HeavyWolf,
Would it be possible to fix the markdown #, ##, ###...etc  title colors of blog to correspond with the dark theme?
https://patagon.uach.cl/

And if its possible, is there a way to make the blog posts appear in such a way that it can be easier to identify the newer from the older? maybe just a top-down ordering from newest to older.

Again, many thanks for this contribution.

**Comment by Wafelowski** [comment]
I've fixed the titles, but I'm trying to improve the mobile menu so the release will have to wait. About the blog order, you can set it in Admin panel in page settings, 
![image](https://user-images.githubusercontent.com/47658430/114093556-8d306f00-98bb-11eb-821d-2a6b2ca4d823.png)

**Comment by Wafelowski** [comment]
Nevermind, new release has the fix.

**Comment by crinavar** [comment]
Hi HeavyWolf, I've Just applied the recent theme update but for some reason I am not getting the fix in the title colors. Let me know if you want me to check something

**Comment by crinavar** [comment]
> I've fixed the titles, but I'm trying to improve the mobile menu so the release will have to wait. About the blog order, you can set it in Admin panel in page settings,
> ![image](https://user-images.githubusercontent.com/47658430/114093556-8d306f00-98bb-11eb-821d-2a6b2ca4d823.png)

Thanks, missed that menu.

**Comment by Wafelowski** [comment]
No problem, I'll leave it open in case you find anything that needs fixing,

**Comment by crinavar** [comment]
Thanks,
The titles still appear dark in the blog page. Any ideas?

**Comment by Wafelowski** [comment]
Try latest release

**Comment by crinavar** [comment]
Hi HeavyWolf,
For some reason I am not getting an update option on grav menu for the latest changes of 1.0.4-2

**Comment by crinavar** [comment]
Dont Worry HeavyWolf, 
I realized that I wont be using the Blog mode, I've embedded a twitter account activity in the front page. Works best in the current times. Thanks for the help.

**Comment by Wafelowski** [comment]
No problem, it seems I messed something up when making the latest release. Should be fixed soon, thanks for reporting bugs.
