### ISSUE TITLE
Logo width

### ISSUE THREAD

**Issue by multimill** [HeavyWolfPL/grav-theme-darkquark#5]
Hello,

I did a fresh install of Grav with onyl this theme and two plugins (anchors and Markdown Collapsible) installed.

As soon as I add a third page the navigation bar drops below the line and the design is f***** up. I somehow need to change the width of the logo which seems to be fixed. But I don't have any clue how to do so.

![firefox_2021-05-08_20-23 (2)](https://user-images.githubusercontent.com/24725624/117549609-ae5fb900-b03b-11eb-9e0b-a36e10d8a978.png)

Can you tell me how I can fix this? This does only happen in darkquark but not in the normal quark theme:

![firefox_2021-05-08_20-23 (3)](https://user-images.githubusercontent.com/24725624/117549652-e961ec80-b03b-11eb-996c-3c6164859766.png)

Thanks in advance!

**Comment by Wafelowski** [comment]
I will check it out as fast as I get home.

**Comment by multimill** [comment]
I just uploaded my own logo and this "repairs" the site and everything is fine now. You can even upload the default logo and set it as custom logo and it will be fine.

So there is something wrong with the default logo.
