### ISSUE TITLE
[FIX MERGED] grav-logo.svg included in theme buggy. Fix proposed.

### ISSUE THREAD

**Issue by dudeitssm** [HeavyWolfPL/grav-theme-darkquark#6]
Hi Wolf.

The grav-logo.svg included in this theme is "offset", especially when in mobile view. I did also compare the source code of the svg itself, and it differs in many places from the grav-logo.svg present in the Quark theme.

You can find the properly functioning logo from here: https://github.com/getgrav/grav-theme-quark/blob/develop/images/grav-logo.svg

The problem is emphasized in red. Left side, Quark theme; right side, Quark Dark theme:
![quark_vs_dark_quark](https://user-images.githubusercontent.com/36095297/136481586-632513b0-c199-4dde-a4ae-3dd5b775a7d4.png)

![quark_vs_dark_quark_mobile](https://user-images.githubusercontent.com/36095297/136482008-e7d0dad8-381d-403b-9803-1468f467c51f.png)

To solve this issue, I simply overwrote the svg included with the one provided by the Quark theme.
You can see the difference below:
![quark_vs_dark_quark_mobile_2](https://user-images.githubusercontent.com/36095297/136482232-053788aa-711a-4485-af0e-9a63c0c85bd6.png)

**Comment by Wafelowski** [comment]
https://github.com/HeavyWolfPL/grav-theme-darkquark/commit/64a0e85415be541c0fe64bad7b53734df9899b76

1.0.6 contains a fix, I think it works?

**Comment by dudeitssm** [comment]
Confirmed. The sha256sum is an exact match. 
**This update fixes the issue mentioned in this open issue regarding the Grav logo offset.**

There is another issue I found, that is the login screen theme is white on black, instead of black on white. I will make another PR about that tomorrow, or very shortly.

Thank you! I will close this issue.
